buildscript {
    repositories {
        mavenCentral()
        maven { url = "https://files.minecraftforge.net/maven" }
    }
    dependencies {
        classpath 'com.anatawa12.forge:ForgeGradle:2.3-1.0.+'
    }
}
apply plugin: 'net.minecraftforge.gradle.forge'

version = mod_version
group = "net.minecraft.gargoyles" // http://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = mod_id

sourceCompatibility = targetCompatibility = '1.8' // Need this here so eclipse task generates correctly.
compileJava {
    sourceCompatibility = targetCompatibility = '1.8'
}

minecraft {
    version = "1.12.2-14.23.5.2847"
    runDir = "run"
    mappings = "snapshot_20180104"
}

repositories {
    mavenCentral()
    maven { url 'https://www.cursemaven.com'}
}

dependencies {
    runtime "curse.maven:jei-238222:2988828"
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'

        expand 'version':project.version, 'mcversion':project.minecraft.version

        duplicatesStrategy = DuplicatesStrategy.INCLUDE
    }
}